apiVersion: v1
kind: Pod
metadata:
  name: ding-test
  namespace: default
spec:
  containers:
  - name: container1
    image: apache/simple-web:v1
    imagePullPolicy: IfNotPresent
    readinessProbe:
      httpGet:
        port: 80
        path: /index.html
      initialDelaySeconds: 1
      periodSeconds: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: ding-test
  namespace: default
spec:
  containers:
  - name: container1
    image: apache/simple-web:v1
    imagePullPolicy: IfNotPresent
    command: ["touch /test-live ; sleep 10 ; rm -rf /test-live"]
    livenessProbe:
      exec:
        command: ["test", "-e", "/test-live"]
      initialDelaySeconds: 1
      periodSeconds: 3
---
apiVersion: v1
kind: Pod
metadata:
  name: ding-test
  namespace: default
spec:
  containers:
  - name: container1
    image: apache/simple-web:v1
    livenessProbe:
      httpGet:
        port: 80
        path: /index.html
      initialDelaySeconds: 1
      periodSeconds: 3
      timeoutSeconds: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: ding-test
  namespace: default
spec:
  containers:
  - name: container1
    image: apache/simple-web:v1
    imagePullPolicy: IfNotPresent
    command: ["touch /test-live ; sleep 10 ; rm -rf /test-live"]
    livenessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      timeoutSeconds: 1